import { HardwareSelector } from "@/app/components/hardware-selector";
import { chipProfiles, type Chip, type ConfigFieldErrors } from "@/lib/hardware";

type FormConfig = { chip?: string; memoryGb?: number; diskGb?: number; workload?: string; runtime?: string; context?: string };

export function FinderForm({ config, submitted, errors, fieldErrors, catalogueError }: { config: FormConfig; submitted: boolean; errors: string[]; fieldErrors: ConfigFieldErrors; catalogueError: string }) {
  const selectedChip: Chip = typeof config.chip === "string" && config.chip in chipProfiles ? config.chip as Chip : "m4";
  return <section className="finder" id="finder" aria-labelledby="finder-title"><div className="section-intro"><span className="eyebrow">01 — Your machine</span><h2 id="finder-title">Build your Mac profile</h2><p>We use these details only to calculate this recommendation. They are sent with this page request and are not saved.</p></div>
    <form method="get" aria-describedby="configuration-help">{submitted && errors.length > 0 && <div className="error-summary" role="alert" tabIndex={-1} autoFocus><h2>Check your Mac profile</h2><p>Correct the following before finding models:</p><ul>{errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}<p id="configuration-help" className="form-help">Your choices stay in this page link only; we do not save your Mac profile.</p><fieldset className="form-section hardware-section"><legend>Hardware</legend><p className="section-help">Use the numbers shown in Apple menu → About This Mac, plus the storage currently available in System Settings.</p><details className="specs-helper"><summary>Find your Mac specs</summary><div><p><b>Chip</b> is the Apple chip name, such as M1, M3 Pro, or M4 Max.</p><p><b>Unified memory</b> is the RAM shared by your Mac’s processor and graphics—not the amount currently in use.</p><p><b>Free disk space</b> is storage available now for downloading a model; leave room for macOS and your files.</p></div></details><div className="fields"><HardwareSelector chip={selectedChip} memoryGb={config.memoryGb ?? 16} fieldErrors={fieldErrors}/><label htmlFor="diskGb">Free disk space (GB)<input id="diskGb" name="diskGb" required min="1" max="4000" type="number" defaultValue={config.diskGb ?? 80} aria-invalid={Boolean(fieldErrors.diskGb)} aria-describedby={fieldErrors.diskGb ? "disk-error" : undefined}/>{fieldErrors.diskGb && <span className="field-error" id="disk-error">{fieldErrors.diskGb}</span>}</label></div></fieldset>
      <fieldset className="form-section" aria-describedby={fieldErrors.workload ? "workload-error" : undefined} aria-invalid={Boolean(fieldErrors.workload)}><legend>What do you want to do?</legend><p className="section-help">Pick the outcome you want most. <b>Not sure?</b> Choose Balanced for a good starting point.</p><span className="control-label">Your main use</span><div className="choices workload">{(["chat", "coding", "balanced"] as const).map((workload) => <label key={workload}><input name="workload" type="radio" value={workload} required={workload === "chat"} defaultChecked={(config.workload ?? "balanced") === workload}/><span>{workload === "chat" ? "Ask questions and write" : workload === "coding" ? "Write and understand code" : "Balanced · not sure"}</span></label>)}</div>{fieldErrors.workload && <span className="field-error" id="workload-error">{fieldErrors.workload}</span>}<span className="control-label context-label">How much text or code in one conversation?</span><p className="section-help">This is called context. <b>Not sure?</b> Normal covers most chats and coding tasks.</p><div className="choices context">{([ ["small", "Short · 4K", "A few messages or a small file"], ["normal", "Normal · 16K", "Typical chat or coding · recommended"], ["long", "Long · 32K", "Large documents or repositories"] ] as const).map(([context, label, description]) => <label key={context}><input name="context" type="radio" value={context} required={context === "small"} defaultChecked={(config.context ?? "normal") === context}/><span><b>{label}</b><small>{description}</small></span></label>)}</div>{fieldErrors.context && <span className="field-error" id="context-error">{fieldErrors.context}</span>}</fieldset>
      <fieldset className="form-section" aria-describedby={fieldErrors.runtime ? "runtime-error" : undefined} aria-invalid={Boolean(fieldErrors.runtime)}><legend>How would you like to run it?</legend><p className="section-help"><b>Not sure?</b> Ollama is the simplest starting point: install one app, then use a short command to run a model.</p><div className="choices">{([ ["ollama", "Ollama · recommended"], ["lmStudio", "LM Studio"], ["mlx", "MLX"], ["llamaCpp", "llama.cpp"] ] as const).map(([runtime, label]) => <label key={runtime}><input name="runtime" type="radio" value={runtime} required={runtime === "ollama"} defaultChecked={(config.runtime ?? "ollama") === runtime}/><span>{label}</span></label>)}</div>{fieldErrors.runtime && <span className="field-error" id="runtime-error">{fieldErrors.runtime}</span>}</fieldset>
      <button type="submit">Find compatible models <span aria-hidden="true">→</span></button>{catalogueError && <p className="error" role="alert">{catalogueError}</p>}
    </form>
  </section>;
}
