import { HardwareSelector } from "@/app/components/hardware-selector";
import { chipProfiles, type Chip, type ConfigFieldErrors } from "@/lib/recommendations";

type FormConfig = { chip?: string; memoryGb?: number; diskGb?: number; workload?: string; runtime?: string; context?: string };

export function FinderForm({ config, submitted, errors, fieldErrors, catalogueError }: { config: FormConfig; submitted: boolean; errors: string[]; fieldErrors: ConfigFieldErrors; catalogueError: string }) {
  const selectedChip: Chip = typeof config.chip === "string" && config.chip in chipProfiles ? config.chip as Chip : "m4";
  return <section className="finder" id="finder" aria-labelledby="finder-title"><div className="section-intro"><span className="eyebrow">01 — Your machine</span><h2 id="finder-title">Build your Mac profile</h2><p>We use these details only to calculate this recommendation. They are sent with this page request and are not saved.</p></div>
    <form method="get" aria-describedby="configuration-help">{submitted && errors.length > 0 && <div className="error-summary" role="alert" tabIndex={-1} autoFocus><h2>Check your Mac profile</h2><p>Correct the following before finding models:</p><ul>{errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}<p id="configuration-help" className="form-help">Chip and unified-memory choices are checked against real Mac configurations.</p><fieldset className="form-section hardware-section"><legend>Hardware</legend><p className="section-help">Set the available memory and storage for this Mac.</p><div className="fields"><HardwareSelector chip={selectedChip} memoryGb={config.memoryGb ?? 16} fieldErrors={fieldErrors}/><label htmlFor="diskGb">Free disk space (GB)<input id="diskGb" name="diskGb" required min="1" max="4000" type="number" defaultValue={config.diskGb ?? 80} aria-invalid={Boolean(fieldErrors.diskGb)} aria-describedby={fieldErrors.diskGb ? "disk-error" : undefined}/>{fieldErrors.diskGb && <span className="field-error" id="disk-error">{fieldErrors.diskGb}</span>}</label></div></fieldset>
      <fieldset className="form-section" aria-describedby={fieldErrors.workload ? "workload-error" : undefined} aria-invalid={Boolean(fieldErrors.workload)}><legend>Use and context</legend><p className="section-help">Choose the work you do most and the room each conversation needs.</p><span className="control-label">What will you do most?</span><div className="choices workload">{(["chat", "coding", "balanced"] as const).map((workload) => <label key={workload}><input name="workload" type="radio" value={workload} required={workload === "chat"} defaultChecked={(config.workload ?? "balanced") === workload}/><span>{workload === "chat" ? "General chat" : workload === "coding" ? "Coding" : "Balanced"}</span></label>)}</div>{fieldErrors.workload && <span className="field-error" id="workload-error">{fieldErrors.workload}</span>}<span className="control-label context-label">How much context do you need?</span><div className="choices context">{([ ["small", "Small", "Short chats"], ["normal", "Normal", "Typical chat or coding"], ["long", "Long", "Large documents or repositories"] ] as const).map(([context, label, description]) => <label key={context}><input name="context" type="radio" value={context} required={context === "small"} defaultChecked={(config.context ?? "normal") === context}/><span><b>{label}</b><small>{description}</small></span></label>)}</div>{fieldErrors.context && <span className="field-error" id="context-error">{fieldErrors.context}</span>}</fieldset>
      <fieldset className="form-section" aria-describedby={fieldErrors.runtime ? "runtime-error" : undefined} aria-invalid={Boolean(fieldErrors.runtime)}><legend>Runtime</legend><p className="section-help">We only show files that work directly in this app.</p><div className="choices">{([ ["ollama", "Ollama"], ["lmStudio", "LM Studio"], ["llamaCpp", "llama.cpp"], ["mlx", "MLX"] ] as const).map(([runtime, label]) => <label key={runtime}><input name="runtime" type="radio" value={runtime} required={runtime === "ollama"} defaultChecked={(config.runtime ?? "ollama") === runtime}/><span>{label}</span></label>)}</div>{fieldErrors.runtime && <span className="field-error" id="runtime-error">{fieldErrors.runtime}</span>}</fieldset>
      <button type="submit">Find compatible models <span aria-hidden="true">→</span></button>{catalogueError && <p className="error" role="alert">{catalogueError}</p>}
    </form>
  </section>;
}
